version: "3"

services:
  users:
    build: ./user_service
    
  cars:
    build: ./car_service
  
  books:
    build: ./book_service
  
  monolith:
    build: ./monolith

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cars
      - books
      - users
      - monolith
